import Head from "next/head";
import React from "react";

function Seo() {
  return (
    <Head>
      <title>Fitjoe</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
}

export default Seo;
